# modules in python------

In [2]:
import camelcase # it gives us error cause we didnt install this package

 installing camelcase package

In [18]:
pip install camelcase

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [16]:
import camelcase

In [17]:
from camelcase import CamelCase
c = CamelCase()
s = 'this is a sentence that needs CamelCasing!'
print(c.hump(s))
# This is a Sentence That Needs CamelCasing!

This is a Sentence That Needs CamelCasing!


In [4]:
# importing local package*******************

In [9]:
from package import module

In [11]:
print(module.add(10,52))

62


In [12]:
print(module.sub(50,10))

40


In [14]:
print(module.multi(10,80))

800


# exploring different packages-

In [306]:
import os

In [311]:
#gives path of current file  (get current working directory)
path = os.getcwd()
print(path)

C:\Users\Pranali\Desktop\python


In [308]:
# change path of current directory
os.chdir(r'C:\Users\Pranali\Desktop\python')

In [309]:
print(path)

C:\Users\Pranali\Desktop\python


In [310]:
# make directory
os.mkdir(r'C:\Users\Pranali\Desktop\python\new2.ipynb')

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Pranali\\Desktop\\python\\new2.ipynb'

In [82]:
# delet a empty directory
print(os.remove(r'C:\Users\Pranali\Desktop\python/python-modules-and-packages/empty-directory.ipynb'))

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Pranali\\Desktop\\python/python-modules-and-packages/empty-directory.ipynb'

# import datetime

In [292]:
import datetime

In [293]:
#check date and time
datetime = datetime.datetime.now()
print(datetime)

2025-06-13 10:27:10.793616


In [294]:
print(datetime.strftime('%H:%M:%S %D'))

10:27:10 06/13/25


In [295]:
print(datetime.today())

2025-06-13 10:27:15.272135


# import math

In [296]:
import math

In [102]:
# calculate factorial
print(math.factorial(5))

120


In [312]:
#square root
print(math.isqrt(16))

4


In [121]:
#floating point arithmetic

In [129]:
#ciel of x means (it gives roundoff number greater than input)
print(math.ceil(3.1))

4


In [135]:
# floor of x (it gives roundoff number less than input)
print(math.floor(3.9))

3


In [298]:
#sum
print(math.fsum([5,4,5,5,5]))

24.0


In [153]:
# cos sin tan
print(math.sin(1/2))
print(math.cos(5))
print(math.tan(1))

0.479425538604203
0.28366218546322625
1.5574077246549023


In [158]:
print(math.pi)

3.141592653589793


# import statistics

In [305]:
import statistics

In [307]:
#find mean (average)
list =[1,2,3,4,5,6,7,8]
print(statistics.mean(list))

4.5


In [166]:
# finding median 
print(statistics.median(list))

4.5


# import random

In [308]:
import random

In [311]:
# give a random integer in between the range give by user
print(random.randint(2,11))

11


In [195]:
# shuffle a input
list = [1,2,3,4,5,6,7,8,9]
random.shuffle(list)
print(list)

[3, 2, 9, 8, 5, 7, 1, 6, 4]


In [317]:
#gives random floating point in range
random.uniform(2,7)

5.024161729102176

# import numpy as np

In [12]:
import numpy as np

In [3]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# multi dimensional array
print(np.array([[1,2,3],[4,5,6],[7,8,9]]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# use for intializing
print(np.zeros((2,3)))
print(np.ones((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# converting 1d array to any dimention
list1 = [1,2,3,4,5,6,7,8,9]
arr = np.arange(12)
print(arr)
print(arr.reshape((4,3)))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [47]:
# used for switch rows and columns - transpose (.T)
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [51]:
# finding total , average and veriablity
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr) 

print(arr.sum())
print(arr.mean())
print(arr.std())

[[1 2 3 4]
 [5 6 7 8]]
36
4.5
2.29128784747792


In [63]:
# multiply two array - in below example - 1*4, 2*2, 3*3, 4*4
x = np.array([1,2,3,4])
y = np.array([4,2,3,4])
print(np.dot(x,y))


33


In [67]:
# multiplication of 2d array
x = np.array([[1,2],[4,5]])
y = np.array([[8,9],[7,4]])

print(np.dot(x,y))

[[22 17]
 [67 56]]


In [69]:
#generate random data
random = np.random.random((3,3))
print(random)

[[0.79827216 0.84663422 0.98423832]
 [0.4627703  0.26199101 0.85938089]
 [0.12553564 0.36392813 0.38887752]]


In [70]:
print(np.random.random((2,2)))

[[0.10180983 0.15626109]
 [0.09327728 0.99823616]]


In [271]:
from numpy.linalg import inv
A = np.array([[2., 3.], [1., 4.]])
print(inv(A))

[[ 0.8 -0.6]
 [-0.2  0.4]]


### examples on Numpy

In [304]:
# exmples------------------------------------------------------------------------------
#Generate a 4×5 matrix of random numbers Print the shape, mean, and standard deviation
random = np.random.random((4,5))
print(random)

[[0.66166392 0.40586165 0.92260786 0.98965377 0.36375447]
 [0.33962091 0.48699208 0.79424635 0.3340494  0.20040733]
 [0.39383267 0.9206647  0.7404574  0.82299282 0.26163546]
 [0.14579954 0.14449891 0.9929699  0.62014347 0.04776126]]


In [283]:
print(np.shape(random))
print(np.mean(random))
print(np.std(random))

(4, 5)
0.4893641929817575
0.30808565909902397


In [292]:
# create 1D array and make it 3*4 array (reshape)
random = np.arange(1,13)
print(random)
print(random.reshape(3,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [318]:
#total sum of all elements 
#Mean of each column
#Standard deviation of each row
A = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
print(A.sum())
print(A.mean(axis=1))
print(A.std(axis=1))

450
[20. 50. 80.]
[8.16496581 8.16496581 8.16496581]


In [1]:
## heading

# import pandas

In [75]:
import pandas as pd

In [191]:
# it shows .csv file into data frame
data = pd.read_csv('data.csv')

In [192]:
print(data)

   EmployeeID     Name  Age Department  Salary  StartDate social
0           1    Alice   29         HR   50000  1/15/2020      t
1           2      Bob   35         IT   65000  7/22/2019      t
2           3  Charlie   32    Finance   60000  12/1/2018      t
3           4    David   28         IT   50000  3/10/2021      t
4           5      Eva   28         HR   52000  6/25/2020      t
5           6    Frank   40    Finance   80000  9/13/2017      t


In [193]:
# access to first 3 rows
print(data.head(3))

   EmployeeID     Name  Age Department  Salary  StartDate social
0           1    Alice   29         HR   50000  1/15/2020      t
1           2      Bob   35         IT   65000  7/22/2019      t
2           3  Charlie   32    Finance   60000  12/1/2018      t


In [194]:
# access to last 2 rows
print(data.tail(2))

   EmployeeID   Name  Age Department  Salary  StartDate social
4           5    Eva   28         HR   52000  6/25/2020      t
5           6  Frank   40    Finance   80000  9/13/2017      t


In [195]:
#inspect info
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   EmployeeID  6 non-null      int64 
 1   Name        6 non-null      object
 2   Age         6 non-null      int64 
 3   Department  6 non-null      object
 4   Salary      6 non-null      int64 
 5   StartDate   6 non-null      object
 6   social      6 non-null      object
dtypes: int64(3), object(4)
memory usage: 468.0+ bytes
None


In [196]:
# data size
print(data.shape)

(6, 7)


In [197]:
# describe data
print(data.describe())

       EmployeeID        Age      Salary
count    6.000000   6.000000      6.0000
mean     3.500000  32.000000  59500.0000
std      1.870829   4.774935  11726.0394
min      1.000000  28.000000  50000.0000
25%      2.250000  28.250000  50500.0000
50%      3.500000  30.500000  56000.0000
75%      4.750000  34.250000  63750.0000
max      6.000000  40.000000  80000.0000


In [198]:
#access perticular data from csv file
david = data.loc[0:,['Name','StartDate','Salary']]
print(david)

      Name  StartDate  Salary
0    Alice  1/15/2020   50000
1      Bob  7/22/2019   65000
2  Charlie  12/1/2018   60000
3    David  3/10/2021   50000
4      Eva  6/25/2020   52000
5    Frank  9/13/2017   80000


In [201]:
# acccess data from row and column
print(data.iloc[0:2,0:])

   EmployeeID   Name  Age Department  Salary  StartDate social
0           1  Alice   29         HR   50000  1/15/2020      t
1           2    Bob   35         IT   65000  7/22/2019      t


In [214]:
# drop column (removes) -  it doesn't change in original data it create modified in separate variable 
drop = data.drop('social', axis=1)
print(drop)

   EmployeeID     Name  Age Department  Salary  StartDate
0           1    Alice   29         HR   50000  1/15/2020
1           2      Bob   35         IT   65000  7/22/2019
2           3  Charlie   32    Finance   60000  12/1/2018
3           4    David   28         IT   50000  3/10/2021
4           5      Eva   28         HR   52000  6/25/2020
5           6    Frank   40    Finance   80000  9/13/2017


In [243]:
data =pd.read_csv('data.csv')

In [240]:
#data['Salary'].fillna(data['Salary'].mean(),inplace=True)

In [244]:
data

EmployeeID     Name  Age Department   Salary  StartDate social
0           1    Alice   29         HR  50000.0  1/15/2020      t
1           2      Bob   35         IT  65000.0  7/22/2019      t
2           3  Charlie   32    Finance  60000.0  12/1/2018      t
3           4    David   28         IT  50000.0  3/10/2021      t
4           5      Eva   28         HR  52000.0  6/25/2020      t
5           6    Frank   40    Finance  80000.0  9/13/2017      t
6           7      Nil   23         IT      NaN  1/20/2025      t

In [258]:
# it fills empty values - fillna(value,inplace = True)
data['Salary'].fillna(2000,inplace = True)

In [259]:
data

EmployeeID     Name  Age Department   Salary  StartDate social
0           1    Alice   29         HR  50000.0  1/15/2020      t
1           2      Bob   35         IT  65000.0  7/22/2019      t
2           3  Charlie   32    Finance  60000.0  12/1/2018      t
3           4    David   28         IT  50000.0  3/10/2021      t
4           5      Eva   28         HR  52000.0  6/25/2020      t
5           6    Frank   40    Finance  80000.0  9/13/2017      t
6           7      Nil   23         IT   2000.0  1/20/2025      t

In [269]:
# count numbers on each department
data['Department'].value_counts()

Department
IT         3
HR         2
Finance    2
Name: count, dtype: int64

In [274]:
data['Salary'].value_counts()

Salary
50000.0    2
65000.0    1
60000.0    1
52000.0    1
80000.0    1
2000.0     1
Name: count, dtype: int64

In [284]:
# show group and aggregate - (it shows average salary of each department)
data.groupby('Department')['Salary'].mean()


Department
Finance    70000.0
HR         51000.0
IT         39000.0
Name: Salary, dtype: float64

In [290]:
# sort a data with salary - (it gives values according to salary like below)
data.sort_values('Salary')

EmployeeID     Name  Age Department   Salary  StartDate social
6           7      Nil   23         IT   2000.0  1/20/2025      t
0           1    Alice   29         HR  50000.0  1/15/2020      t
3           4    David   28         IT  50000.0  3/10/2021      t
4           5      Eva   28         HR  52000.0  6/25/2020      t
2           3  Charlie   32    Finance  60000.0  12/1/2018      t
1           2      Bob   35         IT  65000.0  7/22/2019      t
5           6    Frank   40    Finance  80000.0  9/13/2017      t